import { SUPABASE_URL, SUPABASE_ANON_KEY, CONFIGURED } from './config.js';
let createClient;if(CONFIGURED)({createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'));
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sb=CONFIGURED?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;let data={},editing={};if(CONFIGURED)$('#configNotice').classList.add('hidden');
const flash=(text,ok=true)=>{const e=$('#globalStatus');e.className=ok?'ok':'error';e.textContent=text;setTimeout(()=>e.textContent='',3500)};
const field=(n,l,t='text',v='')=>`<label class="${t==='textarea'?'full':''}">${l}${t==='textarea'?`<textarea name="${n}">${esc(v)}</textarea>`:`<input name="${n}" type="${t}" value="${esc(v)}">`}</label>`;
const bool=v=>v===true||v==='true'||v==='on';
const empty=t=>`<div class="empty">${t}</div>`;
async function boot(){if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(session)showDashboard()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!sb){$('#loginStatus').textContent='กรุณาตั้งค่า Supabase ใน config.js';return}const f=Object.fromEntries(new FormData(e.target)),{error}=await sb.auth.signInWithPassword(f);if(error){$('#loginStatus').className='error';$('#loginStatus').textContent=error.message;return}const claim=await sb.rpc('claim_profile');if(claim.error){await sb.auth.signOut();$('#loginStatus').textContent=claim.error.message;return}showDashboard()};
async function showDashboard(){$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');await load()}
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
$('#adminMenuToggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('menuOpen');
function goPanel(name){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+name));document.querySelectorAll('.sideNav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));if(innerWidth<=920)document.querySelector('.sidebar').classList.remove('menuOpen')}
$('#sideNav').onclick=e=>{if(!e.target.dataset.panel)return;goPanel(e.target.dataset.panel)};
async function loadAnalytics(){
  if(!sb)return{pageViews:null,top:[]};
  try{
    const[pv,proj]=await Promise.all([
      sb.from('analytics_events').select('id',{count:'exact',head:true}).eq('type','page_view'),
      sb.from('analytics_events').select('project_id').eq('type','project_view')
    ]);
    if(pv.error||proj.error)throw(pv.error||proj.error);
    const counts={};
    (proj.data||[]).forEach(r=>{if(r.project_id)counts[r.project_id]=(counts[r.project_id]||0)+1});
    const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,count])=>({id,count,title:(data.projects.find(p=>String(p.id)===String(id))||{}).title||('#'+id)}));
    return{pageViews:pv.count||0,top};
  }catch(e){return{pageViews:null,top:[],error:e.message||String(e)}}
}
async function load(){const names=['profiles','projects','skills','messages','practicums','documents','reflections','site_settings'];const qs=[sb.from('profiles').select('*').eq('id',1).single(),sb.from('projects').select('*').order('academic_year').order('sort_order'),sb.from('skills').select('*').order('sort_order'),sb.from('messages').select('*').order('created_at',{ascending:false}),sb.from('practicums').select('*').order('academic_year').order('sort_order'),sb.from('documents').select('*').order('sort_order'),sb.from('reflections').select('*').order('academic_year').order('semester'),sb.from('site_settings').select('*').eq('id',1).single()];const rs=await Promise.all(qs);for(let i=0;i<rs.length;i++)if(rs[i].error){flash(`${names[i]}: ${rs[i].error.message}`,false);return}data={profile:rs[0].data,projects:rs[1].data,skills:rs[2].data,messages:rs[3].data,practicums:rs[4].data,documents:rs[5].data,reflections:rs[6].data,settings:rs[7].data};data.analytics=await loadAnalytics();render()}
const profileFields=[['name_th','ชื่อภาษาไทย'],['name_en','ชื่อภาษาอังกฤษ'],['headline','คำโปรย'],['intro','ข้อความแนะนำ','textarea'],['bio','เกี่ยวกับฉัน','textarea'],['email','อีเมล'],['phone','โทรศัพท์'],['facebook','Facebook'],['line_id','LINE'],['address','ที่อยู่','textarea'],['university','มหาวิทยาลัย'],['faculty','คณะ'],['major','สาขา'],['student_id','รหัสนักศึกษา'],['start_year','ปีเริ่มเรียน','number'],['expected_graduation_year','ปีที่คาดว่าจะจบ','number'],['photo_url','URL รูปโปรไฟล์'],['resume_url','URL Resume']];
function table(cols,rows,kind){return`<div class="tableWrap"><table><thead><tr>${cols.map(x=>`<th>${x[1]}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(x=>`<td>${typeof r[x[0]]==='boolean'?(r[x[0]]?'ใช่':'ไม่'):esc(r[x[0]])}</td>`).join('')}<td><div class="rowActions">${kind==='message'?`<button class="button small" data-read="${r.id}">อ่านแล้ว</button>`:`<button class="button small" data-edit="${kind}" data-id="${r.id}">แก้ไข</button>`}<button class="button small danger" data-delete="${kind}" data-id="${r.id}">ลบ</button></div></td></tr>`).join('')||'<tr><td colspan="9">ยังไม่มีข้อมูล</td></tr>'}</tbody></table></div>`}
function completion(){
  const p=data.profile;
  const checks=[
    ['ข้อมูลส่วนตัวพื้นฐาน (ชื่อ/คำโปรย/แนะนำตัว/เกี่ยวกับฉัน)',!!(p.name_th&&p.headline&&p.intro&&p.bio),'profile'],
    ['รูปโปรไฟล์',!!p.photo_url,'profile'],
    ['Resume',!!p.resume_url,'profile'],
    ['ข้อมูลติดต่อ (อีเมล/โทรศัพท์)',!!(p.email&&p.phone&&p.phone!=='—'),'profile'],
    ['ผลงานปี 1',data.projects.some(x=>x.academic_year===1),'projects',1],
    ['ผลงานปี 2',data.projects.some(x=>x.academic_year===2),'projects',2],
    ['ผลงานปี 3',data.projects.some(x=>x.academic_year===3),'projects',3],
    ['ผลงานปี 4',data.projects.some(x=>x.academic_year===4),'projects',4],
    ['ข้อมูลทักษะ',data.skills.length>0,'skills'],
    ['เอกสารที่เผยแพร่แล้ว',data.documents.some(x=>x.published),'documents']
  ];
  const done=checks.filter(x=>x[1]).length,pct=Math.round(done/checks.length*100);
  return`<div class="completionTop"><div><span class="eyebrow">Portfolio Completion</span><br><b>${pct}%</b></div><div>${done}/${checks.length} รายการสมบูรณ์</div></div><div class="completionBar"><i style="width:${pct}%"></i></div><div class="completionGrid">${checks.map(([label,ok,panel,year])=>`<div class="completionItem ${ok?'done':'missing'}"><span>${ok?'✓':'○'} ${label}</span>${ok?'':`<button type="button" data-jump="${panel}" ${year?`data-jump-year="${year}"`:''}>ไปเพิ่ม →</button>`}</div>`).join('')}</div>`;
}
function renderAnalytics(){
  const a=data.analytics||{pageViews:null,top:[]};
  if(a.error){$('#analyticsStats').innerHTML=`<div class="empty">ยังไม่พร้อมใช้งาน — กรุณารัน <code>schema-additions.sql</code> เพื่อสร้างตาราง analytics_events ก่อน<br><small>${esc(a.error)}</small></div>`;$('#analyticsTopProjects').innerHTML='';return}
  $('#analyticsStats').innerHTML=`<article class="card"><span class="eyebrow">ยอดเข้าชมหน้าเว็บ (สะสม)</span><div style="font-size:42px;font-weight:800">${a.pageViews??0}</div></article>`;
  $('#analyticsTopProjects').innerHTML=a.top.length?`<div class="tableWrap"><table><thead><tr><th>ผลงาน</th><th>จำนวนครั้งที่เปิดดู</th></tr></thead><tbody>${a.top.map(x=>`<tr><td>${esc(x.title)}</td><td>${x.count}</td></tr>`).join('')}</tbody></table></div>`:empty('ยังไม่มีข้อมูลการเปิดดูผลงาน');
}
function render(){const cards=[['ผลงาน',data.projects.length,'projects'],['ฝึกสอน/ฝึกงาน',data.practicums.length,'practicums'],['เอกสาร',data.documents.length,'documents'],['บันทึกการเติบโต',data.reflections.length,'reflections'],['ข้อความใหม่',data.messages.filter(x=>x.status==='new').length,'messages']];$('#stats').innerHTML=`<div class="card completionCard">${completion()}</div>`+cards.map(x=>`<article class="card statCard" data-jump="${x[2]}"><span class="eyebrow">${x[0]}</span><div style="font-size:42px;font-weight:800">${x[1]}</div></article>`).join('');renderAnalytics();$('#profileForm').innerHTML=profileFields.map(x=>field(x[0],x[1],x[2],data.profile[x[0]])).join('')+'<div class="full"><button class="button primary">บันทึกข้อมูลส่วนตัว</button></div>';const pyf=$('#projectYearFilter').value;$('#projectsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['category','ประเภท'],['title','ชื่อ'],['published','เผยแพร่']],pyf==='all'?data.projects:data.projects.filter(x=>String(x.academic_year)===pyf),'project');$('#practicumsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['type','ประเภท'],['organization','สถานที่'],['title','หัวข้อ'],['published','เผยแพร่']],data.practicums,'practicum');$('#documentsTable').innerHTML=table([['type','ประเภท'],['title','ชื่อเอกสาร'],['issuer','หน่วยงาน'],['academic_year','ปี'],['published','สาธารณะ']],data.documents,'document');$('#reflectionsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['title','หัวข้อ'],['published','เผยแพร่']],data.reflections,'reflection');$('#skillsTable').innerHTML=table([['name','ทักษะ'],['group_name','กลุ่ม'],['level','ระดับ'],['published','เผยแพร่']],data.skills,'skill');$('#messagesTable').innerHTML=table([['created_at','วันที่'],['name','ชื่อ'],['email','อีเมล'],['message','ข้อความ'],['status','สถานะ']],data.messages,'message');const f=$('#settingsForm');for(const[k,v]of Object.entries(data.settings)){if(!f.elements[k])continue;if(f.elements[k].type==='checkbox')f.elements[k].checked=!!v;else f.elements[k].value=v??''}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.start_year=+v.start_year||null;v.expected_graduation_year=+v.expected_graduation_year||null;const{error}=await sb.from('profiles').update(v).eq('id',1);if(error)return flash(error.message,false);flash('บันทึกข้อมูลส่วนตัวแล้ว');load()};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.target,v={site_title:f.site_title.value,logo_text:f.logo_text.value.trim()||'PA',primary_color:f.primary_color.value,hero_badge:f.hero_badge.value,hero_cta_text:f.hero_cta_text.value,seo_description:f.seo_description.value,og_image_url:f.og_image_url.value||null,footer_text:f.footer_text.value,maintenance_message:f.maintenance_message.value,show_journey:f.show_journey.checked,show_projects:f.show_projects.checked,show_practicums:f.show_practicums.checked,show_documents:f.show_documents.checked,show_reflections:f.show_reflections.checked,show_skills:f.show_skills.checked,show_contact:f.show_contact.checked,maintenance_mode:f.maintenance_mode.checked};const{error}=await sb.from('site_settings').update(v).eq('id',1);if(error)return flash(error.message,false);document.documentElement.style.setProperty('--blue',v.primary_color);flash('บันทึกการตั้งค่าแล้ว');load()};
$('#exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),...data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importBackup').onchange=async e=>{
  const file=e.target.files[0];if(!file)return;
  if(!confirm('การนำเข้าข้อมูลสำรองจะเขียนทับข้อมูลโปรไฟล์/ตั้งค่า และเพิ่ม/อัปเดตรายการที่มี id ตรงกัน ยืนยันหรือไม่?')){e.target.value='';return}
  flash('กำลังนำเข้าข้อมูลสำรอง…');
  try{
    const text=await file.text(),backup=JSON.parse(text);
    if(backup.profile){const{id,...rest}=backup.profile;const{error}=await sb.from('profiles').update(rest).eq('id',1);if(error)throw error}
    if(backup.settings){const{id,...rest}=backup.settings;const{error}=await sb.from('site_settings').update(rest).eq('id',1);if(error)throw error}
    const tableMap={projects:'projects',practicums:'practicums',documents:'documents',reflections:'reflections',skills:'skills'};
    for(const key of Object.keys(tableMap)){
      const rows=backup[key];
      if(Array.isArray(rows)&&rows.length){const{error}=await sb.from(tableMap[key]).upsert(rows,{onConflict:'id'});if(error)throw error}
    }
    flash('นำเข้าข้อมูลสำรองเรียบร้อยแล้ว');load();
  }catch(err){flash('นำเข้าข้อมูลล้มเหลว: '+(err.message||err),false)}
  e.target.value='';
};
const defs={project:{table:'projects',label:'ผลงาน',fields:[['academic_year','ชั้นปี 1-4','number'],['semester','ภาคเรียน 1-3','number'],['category','ประเภท: coursework/activity/volunteer/award/internship/research/media/certificate'],['title','ชื่อผลงาน'],['title_en','ชื่ออังกฤษ'],['summary','คำอธิบายสั้น','textarea'],['problem','ที่มาและปัญหาของโครงงาน','textarea'],['role','บทบาทของคุณ'],['tools','เครื่องมือและเทคโนโลยี (คั่นด้วย comma)'],['process','ขั้นตอนการทำงาน','textarea'],['details','รายละเอียดเพิ่มเติม','textarea'],['learnings','สิ่งที่ได้เรียนรู้','textarea'],['skills','ทักษะที่ใช้ (คั่นด้วย comma)'],['reflection','Reflection หลังจบผลงาน','textarea'],['started_at','วันที่เริ่ม','date'],['ended_at','วันที่สิ้นสุด','date'],['cover_url','URL รูปปก'],['gallery_urls','URL รูปภาพเพิ่มเติม (คั่นด้วย comma)'],['video_url','URL วิดีโอผลงาน'],['media_url','URL สื่อ'],['github_url','ลิงก์ GitHub'],['external_url','ลิงก์เว็บไซต์ / ลิงก์ภายนอก'],['featured','ผลงานเด่น true/false'],['published','เผยแพร่ true/false'],['sort_order','ลำดับ','number']]},practicum:{table:'practicums',label:'ฝึกสอน / ฝึกงาน',fields:[['academic_year','ชั้นปี','number'],['semester','ภาคเรียน','number'],['type','ประเภท: observation/teaching/internship/workshop'],['organization','โรงเรียน / หน่วยงาน'],['title','หัวข้อ'],['description','รายละเอียด','textarea'],['responsibilities','หน้าที่รับผิดชอบ','textarea'],['learning_outcomes','สิ่งที่เรียนรู้','textarea'],['supervisor','อาจารย์นิเทศ / ผู้ดูแล'],['started_at','วันที่เริ่ม','date'],['ended_at','วันที่สิ้นสุด','date'],['cover_url','URL รูปปก'],['evidence_url','URL หลักฐาน'],['published','เผยแพร่ true/false'],['sort_order','ลำดับ','number']]},document:{table:'documents',label:'เอกสาร / เกียรติบัตร',fields:[['type','ประเภท: resume/transcript/certificate/award/teaching_plan/report/other'],['title','ชื่อเอกสาร'],['issuer','หน่วยงานผู้ออก'],['issued_at','วันที่ออก','date'],['description','รายละเอียด','textarea'],['file_url','URL ไฟล์'],['cover_url','URL รูปปก'],['academic_year','ชั้นปี','number'],['published','เปิดสาธารณะ true/false'],['sort_order','ลำดับ','number']]},reflection:{table:'reflections',label:'บันทึกการเติบโต',fields:[['academic_year','ชั้นปี','number'],['semester','ภาคเรียน','number'],['title','หัวข้อ'],['learned','สิ่งที่เรียนรู้','textarea'],['challenge','ความท้าทาย','textarea'],['improvement','สิ่งที่พัฒนา','textarea'],['next_goal','เป้าหมายถัดไป','textarea'],['cover_url','URL รูปปก'],['published','เผยแพร่ true/false']]},skill:{table:'skills',label:'ทักษะ',fields:[['name','ชื่อทักษะ'],['group_name','กลุ่ม'],['level','ระดับ 0-100','number'],['published','เผยแพร่ true/false'],['sort_order','ลำดับ','number']]}};
function open(kind,row={}){editing={kind,id:row.id};const d=defs[kind];$('#modalTitle').textContent=(row.id?'แก้ไข ':'เพิ่ม ')+d.label;$('#modalForm').innerHTML=d.fields.map(x=>field(x[0],x[1],x[2],Array.isArray(row[x[0]])?row[x[0]].join(', '):row[x[0]]??(x[0]==='published'?'true':''))).join('')+'<div class="full"><button class="button primary">บันทึก</button></div>';$('#modal').classList.add('open')}
$('#projectYearFilter').onchange=render;
$('#addProject').onclick=()=>open('project');$('#addPracticum').onclick=()=>open('practicum');$('#addDocument').onclick=()=>open('document');$('#addReflection').onclick=()=>open('reflection');$('#addSkill').onclick=()=>open('skill');$('#close').onclick=e=>{e.preventDefault();$('#modal').classList.remove('open')};
$('#modalForm').onsubmit=async e=>{e.preventDefault();const d=defs[editing.kind],v=Object.fromEntries(new FormData(e.target));['academic_year','semester','sort_order','level'].forEach(k=>{if(k in v)v[k]=v[k]===''?null:+v[k]});['featured','published'].forEach(k=>{if(k in v)v[k]=bool(v[k])});['tools','skills','gallery_urls'].forEach(k=>{if(k in v)v[k]=v[k]?v[k].split(',').map(x=>x.trim()).filter(Boolean):[]});['started_at','ended_at','issued_at'].forEach(k=>{if(k in v&&!v[k])v[k]=null});const q=editing.id?sb.from(d.table).update(v).eq('id',editing.id):sb.from(d.table).insert(v),{error}=await q;if(error)return flash(error.message,false);$('#modal').classList.remove('open');flash('บันทึกข้อมูลแล้ว');load()};
document.body.addEventListener('click',async e=>{const jumpEl=e.target.closest('[data-jump]');if(jumpEl){goPanel(jumpEl.dataset.jump);const jy=jumpEl.dataset.jumpYear;if(jy&&jumpEl.dataset.jump==='projects')open('project',{academic_year:+jy});return}const id=e.target.dataset.id,kind=e.target.dataset.edit;if(kind){const key={project:'projects',practicum:'practicums',document:'documents',reflection:'reflections',skill:'skills'}[kind];open(kind,data[key].find(x=>String(x.id)===String(id)))}if(e.target.dataset.delete){if(!confirm('ยืนยันการลบรายการนี้?'))return;const k=e.target.dataset.delete,t=k==='message'?'messages':defs[k].table,{error}=await sb.from(t).delete().eq('id',id);if(error)return flash(error.message,false);flash('ลบแล้ว');load()}if(e.target.dataset.read){await sb.from('messages').update({status:'read'}).eq('id',e.target.dataset.read);load()}});
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const f=$('#file').files[0],out=$('#uploadStatus');if(!f)return;if(f.size>10*1024*1024){out.className='error';out.textContent='ไฟล์ใหญ่เกิน 10 MB';return}out.textContent='กำลังอัปโหลด…';const path=`${new Date().getFullYear()}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,{error}=await sb.storage.from('portfolio-media').upload(path,f);if(error){out.className='error';out.textContent=error.message;return}const{data:u}=sb.storage.from('portfolio-media').getPublicUrl(path);out.className='ok';out.innerHTML=`อัปโหลดแล้ว คัดลอก URL นี้:<input value="${esc(u.publicUrl)}" readonly onclick="this.select()">`};
boot();
