import { SUPABASE_URL, SUPABASE_ANON_KEY, CONFIGURED } from './config.js';
let createClient;if(CONFIGURED)({createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),sb=CONFIGURED?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
let data={},editing={};if(CONFIGURED)$('#configNotice').classList.add('hidden');
const flash=(text,ok=true)=>{const e=$('#globalStatus');e.className=ok?'ok':'error';e.textContent=text;setTimeout(()=>e.textContent='',4500)};
const bool=v=>v===true||v==='true'||v==='on';
const field=(n,l,t='text',v='')=>{const isBool=t==='boolean';return `<label class="${t==='textarea'?'full':''}">${l}${t==='textarea'?`<textarea name="${n}">${esc(v)}</textarea>`:isBool?`<input name="${n}" type="checkbox" ${bool(v)?'checked':''}>`:`<input name="${n}" type="${t}" value="${esc(v)}">`}</label>`};
const empty=t=>`<div class="empty">${esc(t)}</div>`;
const health=d=>{const p=d.profile||{},s=d.settings||{};let n=45;n+=p.photo_url?8:0;n+=p.resume_url?8:0;n+=p.bio?6:0;n+=p.email?4:0;n+=Math.min(15,d.projects.length*3);n+=Math.min(8,d.skills.length*2);n+=d.documents.length?4:0;n+=s.seo_description?4:0;n+=[d.projects,d.skills,d.documents,d.practicums,d.reflections].filter(a=>a.length>0).length;return Math.min(100,n)};
async function boot(){if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(session)showDashboard()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!sb){$('#loginStatus').textContent='กรุณาตั้งค่า Supabase ใน config.js';return}const f=Object.fromEntries(new FormData(e.target)),r=await sb.auth.signInWithPassword(f);if(r.error){$('#loginStatus').className='error';$('#loginStatus').textContent=r.error.message;return}const claim=await sb.rpc('claim_profile');if(claim.error){await sb.auth.signOut();$('#loginStatus').className='error';$('#loginStatus').textContent=claim.error.message;return}showDashboard()};
async function showDashboard(){$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');await load()}
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#adminMenuToggle').onclick=()=>$('.sidebar').classList.toggle('menuOpen');
function goPanel(name){$$('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+name));$$('.sideNav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));if(innerWidth<=920) $('.sidebar').classList.remove('menuOpen')}
$('#sideNav').onclick=e=>{const b=e.target.closest('[data-panel]');if(b)goPanel(b.dataset.panel)};

async function loadAnalytics(){if(!sb)return{};try{const[all,page,proj,devices]=await Promise.all([sb.from('analytics_events').select('id',{count:'exact',head:true}),sb.from('analytics_events').select('id',{count:'exact',head:true}).eq('type','page_view'),sb.from('analytics_events').select('project_id').eq('type','project_view').not('project_id','is',null),sb.from('analytics_events').select('device').not('device','is',null)]);const counts={};(proj.data||[]).forEach(r=>counts[r.project_id]=(counts[r.project_id]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([id,count])=>({id,count,title:(data.projects.find(p=>String(p.id)===String(id))||{}).title||'#'+id}));const dc={};(devices.data||[]).forEach(r=>dc[r.device||'unknown']=(dc[r.device||'unknown']||0)+1);return{events:all.count||0,pageViews:page.count||0,top,devices:dc,error:all.error||page.error||proj.error||devices.error}}catch(error){return{error}}}
async function loadAudit(){if(!sb)return[];const r=await sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(12);return r.data||[]}
async function loadMedia(){if(!sb)return[];const r=await sb.storage.from('portfolio-media').list('',{limit:20,sortBy:{column:'created_at',order:'desc'}});return (r.data||[]).filter(x=>x.name)}
async function load(){
 const names=['profiles','projects','skills','messages','practicums','documents','reflections','site_settings'];
 const qs=[sb.from('profiles').select('*').eq('id',1).single(),sb.from('projects').select('*').order('academic_year').order('sort_order'),sb.from('skills').select('*').order('sort_order'),sb.from('messages').select('*').order('created_at',{ascending:false}),sb.from('practicums').select('*').order('academic_year').order('sort_order'),sb.from('documents').select('*').order('sort_order'),sb.from('reflections').select('*').order('academic_year').order('semester'),sb.from('site_settings').select('*').eq('id',1).single()];
 const rs=await Promise.all(qs);for(let i=0;i<rs.length;i++)if(rs[i].error){flash(`${names[i]}: ${rs[i].error.message}`,false);return}
 data={profile:rs[0].data,projects:rs[1].data||[],skills:rs[2].data||[],messages:rs[3].data||[],practicums:rs[4].data||[],documents:rs[5].data||[],reflections:rs[6].data||[],settings:rs[7].data,analytics:{},audit:[],media:[]};data.analytics=await loadAnalytics();data.audit=await loadAudit();data.media=await loadMedia();render();
}
const profileFields=[['name_th','ชื่อภาษาไทย'],['name_en','ชื่อภาษาอังกฤษ'],['headline','คำโปรย'],['intro','ข้อความแนะนำ','textarea'],['bio','เกี่ยวกับฉัน','textarea'],['email','อีเมล','email'],['phone','โทรศัพท์'],['facebook','Facebook'],['line_id','LINE'],['address','ที่อยู่','textarea'],['university','มหาวิทยาลัย'],['faculty','คณะ'],['major','สาขา'],['student_id','รหัสนักศึกษา'],['start_year','ปีเริ่มเรียน','number'],['expected_graduation_year','ปีที่คาดว่าจะจบ','number'],['photo_url','URL รูปโปรไฟล์'],['resume_url','URL Resume']];
function table(cols,rows,kind){return `<div class="tableWrap"><table><thead><tr>${cols.map(x=>`<th>${x[1]}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(x=>`<td>${typeof r[x[0]]==='boolean'?(r[x[0]]?'✓':'—'):esc(r[x[0]])}</td>`).join('')}<td><div class="rowActions">${kind==='message'?`<button class="button small" data-read="${r.id}">อ่านแล้ว</button>`:`<button class="button small" data-edit="${kind}" data-id="${r.id}">แก้ไข</button>`}<button class="button small danger" data-delete="${kind}" data-id="${r.id}">ลบ</button></div></td></tr>`).join('')||'<tr><td colspan="8">ยังไม่มีข้อมูล</td></tr>'}</tbody></table></div>`}
function completion(){const p=data.profile,checks=[['ข้อมูลโปรไฟล์',!!(p.name_th&&p.headline&&p.intro&&p.bio),'profile'],['รูปโปรไฟล์',!!p.photo_url,'profile'],['Resume',!!p.resume_url,'profile'],['ช่องทางติดต่อ',!!(p.email&&p.phone&&p.phone!=='—'),'profile'],...([1,2,3,4].map(y=>[`ผลงานปี ${y}`,data.projects.some(x=>+x.academic_year===y),'projects',y])),['ข้อมูลทักษะ',data.skills.length>0,'skills'],['เอกสาร',data.documents.some(x=>x.published),'documents']];const done=checks.filter(x=>x[1]).length,pct=Math.round(done/checks.length*100);return {pct,html:`<div class="completionTop"><div><span class="eyebrow">Portfolio Completion</span><br><b>${pct}%</b></div><div>${done}/${checks.length} รายการ</div></div><div class="completionBar"><i style="width:${pct}%"></i></div><div class="completionGrid">${checks.map(([label,ok,panel,year])=>`<div class="completionItem ${ok?'done':'missing'}"><span>${ok?'✓':'○'} ${label}</span>${ok?'':`<button type="button" data-jump="${panel}" ${year?`data-jump-year="${year}"`:''}>ไปเพิ่ม →</button>`}</div>`).join('')}</div>`}}
function coach(){const tips=[];if(!data.profile.photo_url)tips.push('เพิ่มรูปโปรไฟล์เพื่อสร้างภาพจำใน Hero');if(!data.profile.resume_url)tips.push('เพิ่ม Resume เพื่อให้ Recruiter เปิดดูต่อได้ทันที');for(let y=1;y<=4;y++)if(!data.projects.some(x=>+x.academic_year===y))tips.push(`เติม Project ของปี ${y} เพื่อให้ Timeline สมบูรณ์`);if(!data.projects.some(x=>x.featured))tips.push('เลือก Project เด่นอย่างน้อย 1 ชิ้นเพื่อขึ้น Hero/Selected Work');if(!data.settings.seo_description)tips.push('เติม SEO description เพื่อการแชร์และค้นหา');if(!tips.length)tips.push('Portfolio อยู่ในสภาพพร้อมนำเสนอแล้ว — เพิ่ม Case Study ที่มีผลลัพธ์เชิงตัวเลขต่อได้');return tips}
function renderOverview(){const h=health(data);$('#healthScore').textContent=h;$('#healthBarFill').style.width=h+'%';const cards=[['PROJECTS',data.projects.length,'projects'],['SKILLS',data.skills.length,'skills'],['EXPERIENCE',data.practicums.length,'practicums'],['DOCUMENTS',data.documents.length,'documents'],['NEW MESSAGES',data.messages.filter(x=>x.status==='new').length,'messages'],['PAGE VIEWS',data.analytics.pageViews??0,'analytics']];$('#stats').innerHTML=cards.map(x=>`<button class="metricCard" data-jump="${x[2]}"><span>${x[0]}</span><strong>${x[1]}</strong><small>เปิดจัดการ →</small></button>`).join('');const c=completion();$('#todoList').innerHTML=c.html;$('#coachList').innerHTML=coach().map(t=>`<div class="coachItem"><span>✦</span>${esc(t)}</div>`).join('');$('#recentActivity').innerHTML=data.audit.length?data.audit.map(a=>`<div class="activityRow"><span class="activityDot"></span><div><b>${esc(a.action||'update')}</b><p>${esc(a.entity_type||'content')} ${a.entity_id?`· #${a.entity_id}`:''}</p></div><time>${new Date(a.created_at).toLocaleString('th-TH')}</time></div>`).join(''):empty('ยังไม่มี Audit Log — การเปลี่ยนแปลงใหม่จากเวอร์ชันนี้จะเริ่มบันทึกอัตโนมัติ')}
function renderAnalytics(){const a=data.analytics||{};$('#analyticsStats').innerHTML=[['EVENTS',a.events||0],['PAGE VIEWS',a.pageViews||0],['PROJECT OPENS',(a.top||[]).reduce((n,x)=>n+x.count,0)],['DEVICES',Object.keys(a.devices||{}).length]].map(x=>`<article class="metricCard static"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');$('#analyticsTopProjects').innerHTML='<div class="cardHead"><div><span class="eyebrow">Top Projects</span><h3>ผลงานที่คนเปิดดู</h3></div></div>'+(a.top?.length?`<div class="rankList">${a.top.map((x,i)=>`<div class="rankRow"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x.title)}</span><strong>${x.count}</strong></div>`).join('')}</div>`:empty('ยังไม่มีข้อมูล'));$('#analyticsDevices').innerHTML='<div class="cardHead"><div><span class="eyebrow">Devices</span><h3>อุปกรณ์ผู้ชม</h3></div></div>'+(Object.keys(a.devices||{}).length?Object.entries(a.devices).map(([k,v])=>`<div class="deviceRow"><span>${esc(k)}</span><strong>${v}</strong></div>`).join(''):empty('ยังไม่มีข้อมูล'))}
function renderPublishing(){const rows=[['Profile',!!data.profile.name_th&&!!data.profile.bio],['Projects',data.projects.some(x=>x.published)],['4-Year coverage',[1,2,3,4].every(y=>data.projects.some(x=>+x.academic_year===y))],['Skills',data.skills.some(x=>x.published)],['Documents',data.documents.some(x=>x.published)],['SEO',!!data.settings.seo_description]];$('#publishingChecklist').innerHTML=rows.map(([n,ok])=>`<div class="publishRow"><span>${ok?'✓':'○'} ${n}</span><b class="${ok?'ok':'warn'}">${ok?'READY':'NEEDS WORK'}</b></div>`).join('')}
function renderAudit(){const rows=data.audit||[];$('#auditTable').innerHTML=rows.length?`<div class="tableWrap"><table><thead><tr><th>เวลา</th><th>Action</th><th>Entity</th><th>User</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('th-TH')}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type)} ${a.entity_id?`#${a.entity_id}`:''}</td><td>${esc(a.actor_email||'admin')}</td></tr>`).join('')}</tbody></table></div>`:empty('ยังไม่มี Audit Log')}
function renderMedia(){const rows=data.media||[];$('#mediaLibrary').innerHTML=rows.length?`<div class="mediaList">${rows.map(x=>{const url=sb.storage.from('portfolio-media').getPublicUrl(x.name).data.publicUrl;return `<div class="mediaRow"><span class="mediaIcon">${/\.pdf$/i.test(x.name)?'PDF':'IMG'}</span><div><b>${esc(x.name)}</b><small>${new Date(x.created_at||Date.now()).toLocaleDateString('th-TH')}</small></div><button class="button small" data-copy-url="${esc(url)}">คัดลอก URL</button></div>`}).join('')}</div>`:empty('ยังไม่มีไฟล์')}
function render(){renderOverview();renderAnalytics();renderPublishing();renderAudit();renderMedia();$('#profileForm').innerHTML=profileFields.map(x=>field(x[0],x[1],x[2],data.profile[x[0]])).join('')+'<div class="full"><button class="button primary">บันทึกข้อมูลส่วนตัว</button></div>';const py=$('#projectYearFilter').value,q=($('#projectAdminSearch').value||'').toLowerCase();const pp=data.projects.filter(x=>(py==='all'||String(x.academic_year)===py)&&(!q||[x.title,x.summary,x.category].join(' ').toLowerCase().includes(q)));$('#projectsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['category','ประเภท'],['title','ชื่อ'],['featured','เด่น'],['published','เผยแพร่']],pp,'project');$('#practicumsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['type','ประเภท'],['organization','สถานที่'],['title','หัวข้อ'],['published','เผยแพร่']],data.practicums,'practicum');$('#documentsTable').innerHTML=table([['type','ประเภท'],['title','ชื่อเอกสาร'],['issuer','หน่วยงาน'],['academic_year','ปี'],['published','สาธารณะ']],data.documents,'document');$('#reflectionsTable').innerHTML=table([['academic_year','ปี'],['semester','เทอม'],['title','หัวข้อ'],['published','เผยแพร่']],data.reflections,'reflection');$('#skillsTable').innerHTML=table([['name','ทักษะ'],['group_name','กลุ่ม'],['level','ปัจจุบัน'],['published','เผยแพร่']],data.skills,'skill');$('#messagesTable').innerHTML=table([['created_at','วันที่'],['name','ชื่อ'],['email','อีเมล'],['message','ข้อความ'],['status','สถานะ']],data.messages,'message');const f=$('#settingsForm');for(const[k,v]of Object.entries(data.settings||{})){if(!f.elements[k])continue;if(f.elements[k].type==='checkbox')f.elements[k].checked=!!v;else f.elements[k].value=v??''}}

async function audit(action,entity_type,entity_id=null){try{await sb.from('audit_logs').insert({action,entity_type,entity_id})}catch{}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.start_year=+v.start_year||null;v.expected_graduation_year=+v.expected_graduation_year||null;const{error}=await sb.from('profiles').update(v).eq('id',1);if(error)return flash(error.message,false);await audit('update','profile',1);flash('บันทึกข้อมูลส่วนตัวแล้ว');load()};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.target,v={site_title:f.site_title.value,logo_text:f.logo_text.value.trim()||'PA',primary_color:f.primary_color.value,hero_badge:f.hero_badge.value,hero_cta_text:f.hero_cta_text.value,seo_description:f.seo_description.value,og_image_url:f.og_image_url.value||null,footer_text:f.footer_text.value,maintenance_message:f.maintenance_message.value,show_journey:f.show_journey.checked,show_projects:f.show_projects.checked,show_practicums:f.show_practicums.checked,show_documents:f.show_documents.checked,show_reflections:f.show_reflections.checked,show_skills:f.show_skills.checked,show_contact:f.show_contact.checked,maintenance_mode:f.maintenance_mode.checked};const{error}=await sb.from('site_settings').update(v).eq('id',1);if(error)return flash(error.message,false);await audit('update','site_settings',1);flash('บันทึกการตั้งค่าแล้ว');load()};

const defs={project:{table:'projects',label:'ผลงาน',fields:[['academic_year','ชั้นปี 1-4','number'],['semester','ภาคเรียน 1-3','number'],['category','ประเภท'],['title','ชื่อผลงาน'],['title_en','ชื่ออังกฤษ'],['summary','คำอธิบายสั้น','textarea'],['problem','ที่มาและปัญหา','textarea'],['role','บทบาทของคุณ'],['tools','เครื่องมือ (คั่น comma)'],['process','ขั้นตอนการทำงาน','textarea'],['details','รายละเอียดเพิ่มเติม','textarea'],['learnings','สิ่งที่ได้เรียนรู้','textarea'],['skills','ทักษะ (คั่น comma)'],['reflection','Reflection','textarea'],['started_at','วันที่เริ่ม','date'],['ended_at','วันที่สิ้นสุด','date'],['cover_url','URL รูปปก'],['gallery_urls','URL รูปเพิ่มเติม (คั่น comma)'],['video_url','URL วิดีโอ'],['github_url','GitHub'],['external_url','เว็บไซต์ผลงาน'],['featured','ผลงานเด่น','boolean'],['published','เผยแพร่','boolean'],['sort_order','ลำดับ','number']]},practicum:{table:'practicums',label:'ฝึกสอน / ฝึกงาน',fields:[['academic_year','ชั้นปี','number'],['semester','ภาคเรียน','number'],['type','ประเภท'],['organization','โรงเรียน / หน่วยงาน'],['title','หัวข้อ'],['description','รายละเอียด','textarea'],['responsibilities','หน้าที่รับผิดชอบ','textarea'],['learning_outcomes','สิ่งที่เรียนรู้','textarea'],['supervisor','อาจารย์นิเทศ / ผู้ดูแล'],['started_at','วันที่เริ่ม','date'],['ended_at','วันที่สิ้นสุด','date'],['cover_url','URL รูปปก'],['evidence_url','URL หลักฐาน'],['published','เผยแพร่','boolean'],['sort_order','ลำดับ','number']]},document:{table:'documents',label:'เอกสาร / เกียรติบัตร',fields:[['type','ประเภท'],['title','ชื่อเอกสาร'],['issuer','หน่วยงานผู้ออก'],['issued_at','วันที่ออก','date'],['description','รายละเอียด','textarea'],['file_url','URL ไฟล์'],['cover_url','URL รูปปก'],['academic_year','ชั้นปี','number'],['published','เปิดสาธารณะ','boolean'],['sort_order','ลำดับ','number']]},reflection:{table:'reflections',label:'บันทึกการเติบโต',fields:[['academic_year','ชั้นปี','number'],['semester','ภาคเรียน','number'],['title','หัวข้อ'],['learned','สิ่งที่เรียนรู้','textarea'],['challenge','ความท้าทาย','textarea'],['improvement','สิ่งที่พัฒนา','textarea'],['next_goal','เป้าหมายถัดไป','textarea'],['cover_url','URL รูปปก'],['published','เผยแพร่','boolean']]},skill:{table:'skills',label:'ทักษะ',fields:[['name','ชื่อทักษะ'],['group_name','กลุ่ม'],['level','ระดับปัจจุบัน 0-100','number'],['start_level','ระดับเริ่มต้น 0-100','number'],['target_level','เป้าหมาย 0-100','number'],['published','เผยแพร่','boolean'],['sort_order','ลำดับ','number']]}};
function open(kind,row={}){editing={kind,id:row.id};const d=defs[kind];$('#modalTitle').textContent=(row.id?'แก้ไข ':'เพิ่ม ')+d.label;$('#modalForm').innerHTML=d.fields.map(x=>field(x[0],x[1],x[2],Array.isArray(row[x[0]])?row[x[0]].join(', '):row[x[0]]??(x[2]==='boolean'?true:''))).join('')+'<div class="full"><button class="button primary">บันทึก</button></div>';$('#modal').classList.add('open')}
$('#projectYearFilter').onchange=render;$('#projectAdminSearch').oninput=()=>render();$('#addProject').onclick=()=>open('project');$('#addPracticum').onclick=()=>open('practicum');$('#addDocument').onclick=()=>open('document');$('#addReflection').onclick=()=>open('reflection');$('#addSkill').onclick=()=>open('skill');$('#close').onclick=e=>{e.preventDefault();$('#modal').classList.remove('open')};
$('#modalForm').onsubmit=async e=>{e.preventDefault();const d=defs[editing.kind],v=Object.fromEntries(new FormData(e.target));['academic_year','semester','sort_order','level','start_level','target_level'].forEach(k=>{if(k in v)v[k]=v[k]===''?null:+v[k]});['featured','published'].forEach(k=>{if(k in v)v[k]=bool(v[k])});['tools','skills','gallery_urls'].forEach(k=>{if(k in v)v[k]=v[k]?v[k].split(',').map(x=>x.trim()).filter(Boolean):[]});['started_at','ended_at','issued_at'].forEach(k=>{if(k in v&&!v[k])v[k]=null});const q=editing.id?sb.from(d.table).update(v).eq('id',editing.id):sb.from(d.table).insert(v),{error}=await q;if(error)return flash(error.message,false);await audit(editing.id?'update':'create',d.table,editing.id||null);$('#modal').classList.remove('open');flash('บันทึกข้อมูลแล้ว');load()};

document.body.addEventListener('click',async e=>{const jump=e.target.closest('[data-jump]');if(jump){goPanel(jump.dataset.jump);if(jump.dataset.jumpYear&&jump.dataset.jump==='projects')open('project',{academic_year:+jump.dataset.jumpYear});return}const edit=e.target.closest('[data-edit]');if(edit){const key={project:'projects',practicum:'practicums',document:'documents',reflection:'reflections',skill:'skills'}[edit.dataset.edit];open(edit.dataset.edit,data[key].find(x=>String(x.id)===String(edit.dataset.id)));return}const del=e.target.closest('[data-delete]');if(del){if(!confirm('ยืนยันการลบรายการนี้?'))return;const k=del.dataset.delete,t=k==='message'?'messages':defs[k].table,{error}=await sb.from(t).delete().eq('id',del.dataset.id);if(error)return flash(error.message,false);await audit('delete',t,del.dataset.id);flash('ลบแล้ว');load();return}const read=e.target.closest('[data-read]');if(read){await sb.from('messages').update({status:'read'}).eq('id',read.dataset.read);await audit('read','messages',read.dataset.read);load();return}const copy=e.target.closest('[data-copy-url]');if(copy){await navigator.clipboard.writeText(copy.dataset.copyUrl);copy.textContent='คัดลอกแล้ว ✓';setTimeout(()=>copy.textContent='คัดลอก URL',1500)}});

$('#uploadForm').onsubmit=async e=>{e.preventDefault();const f=$('#file').files[0],out=$('#uploadStatus');if(!f)return;if(f.size>15*1024*1024){out.className='error';out.textContent='ไฟล์ใหญ่เกิน 15 MB';return}out.textContent='กำลังอัปโหลด…';const path=`${new Date().getFullYear()}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,r=await sb.storage.from('portfolio-media').upload(path,f,{upsert:false});if(r.error){out.className='error';out.textContent=r.error.message;return}const u=sb.storage.from('portfolio-media').getPublicUrl(path).data.publicUrl;out.className='ok';out.innerHTML=`อัปโหลดแล้ว <input value="${esc(u)}" readonly>`;await audit('upload','storage');data.media=await loadMedia();renderMedia()};
$('#exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),profile:data.profile,projects:data.projects,skills:data.skills,practicums:data.practicums,documents:data.documents,reflections:data.reflections,settings:data.settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importBackup').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!confirm('นำเข้าข้อมูลสำรองและอัปเดตรายการที่มี id ตรงกันหรือไม่?')){e.target.value='';return}try{const b=JSON.parse(await file.text());if(b.profile){const{id,...rest}=b.profile;await sb.from('profiles').update(rest).eq('id',1)}if(b.settings){const{id,...rest}=b.settings;await sb.from('site_settings').update(rest).eq('id',1)}for(const key of ['projects','skills','practicums','documents','reflections'])if(Array.isArray(b[key])&&b[key].length)await sb.from(key).upsert(b[key],{onConflict:'id'});await audit('import','backup');flash('นำเข้า Backup เรียบร้อย');load()}catch(err){flash('นำเข้าล้มเหลว: '+(err.message||err),false)}e.target.value=''};
boot();
