export const SUPABASE_URL='https://tgoiktctgkxjntbhmrfl.supabase.co';
export const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnb2lrdGN0Z2t4am50YmhtcmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1NzQ1NTQsImV4cCI6MjEwNTE1MDU1NH0.8cmWQmS5HnlaswdXUqgBchP42zdJogYiMZWiXLp8kH0';
export const CONFIGURED= true;
